name: Script check

inputs:
  some:
    description: 'smtng'
    required: true
#    default: '<NOT-PROVIDED-ACTOR>'


runs:
  using: "composite"

  steps:

    - uses: actions/github-script@v7
      with:
        script: |
          console.log('inputs.some: <${{ inputs.some }}>')
          var actor = `${{ inputs.some }}`.trim()
          if (!actor) {
            core.setFailed('Actor was not provided or value is blank')
          }
          

    - uses: actions/github-script@v7
      id: my-script
      with:
        script: |
          console.log('Hello ${{ inputs.some }}')
