name: Script check

inputs:
  some:
    description: 'smtng'
    required: true


runs:
  using: "composite"

  steps:

    - uses: actions/github-script@v7
      id: my-script
      with:
        script: |
          console.log('Hello ${{ inputs.some }}')
