name: Script check

inputs:
  docker-files:
    description: 'An ordered list of docker-compose.yaml files'
    default: |
      docker-compose-1
      docker-compose-2


runs:
  using: "composite"

  steps:

    - name: inputs echo
      shell: bash
      continue-on-error: true
      run: |
        echo 'files ${{ inputs.docker-files }}'

    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        script: |
          return `${{ inputs.docker-files }}`.split('\n')
            .filter(it => it)
            .map(it => `-f ${it}`)
            .join(' ');

    - name: print
      run: |
        echo 'docker compose ${{steps.my-script.outputs.result}} up -d'
        
