name: Script check

inputs:
  docker-files:
    description: 'An ordered list of docker-compose.yaml files'



runs:
  using: "composite"

  steps:

    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        script: |
          var dockerFiles = `${{ inputs.docker-files }}`.trim()
          if (!dockerFiles) {
              throw "'inputs.docker-files' is empty."
          }
          return dockerFiles.split('\n')
              .map(it => it.trim())
              .filter(it => it)
              .map(it => `-f ${it}`)
              .join(' ');

    - name: print
      shell: bash
      run: |
        echo 'docker compose ${{ steps.my-script.outputs.result }} up -d'
        
