name: "Basic Gradle Project Setup"

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'

runs:
  using: "composite"
  steps:

    - name: Vars
      shell: bash
      run: echo "GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}"

    - name: Vars2
      shell: bash
      run: echo "GITHUB_RUN_ID_22=${GITHUB_RUN_ID}"

    - uses: actions/cache@v4
#      post-if: false
      with:
        post-if: false
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
#        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
