name: basic-steps

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: all jobs
        run: echo '${{ toJSON(jobs) }}'

  next-job:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
      - name: all jobs
        run: echo '${{ toJSON(jobs) }}'

      - name: all needs
        run: echo '${{ toJSON(needs) }}'
