name: basic-steps-1

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    env:
      gradle_cmd: "./gradlew --parallel --console=plain --no-watch-fs -s "
      is_pull_request: github.event_name == 'pull_request'

    steps:

      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          go run test.go
