name: basic-steps

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    env:
      gradle_cmd: "./gradlew --parallel --console=plain --no-watch-fs -s "
      is_pull_request: github.event_name == 'pull_request'

    steps:

      - name: Artifacts Publish Enabled
        id: artifacts
        run: |
          echo 'github.ref: ${{ github.ref }}'
          echo 'is master github.ref: ${{ github.ref == 'refs/heads/main' }}'
          echo 'is feature github.ref: ${{ startsWith(github.ref, 'refs/heads/feature/') }}'
          echo 'github.event_name: ${{ github.event_name }}, isPush: ${{ github.event_name == 'push'  }}'
          echo 'check result: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/') }}'
          artifacts_publish_enabled="${{ 
            ( github.event_name == 'push' 
                && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/') ) 
            )
                || contains(github.event.pull_request.labels.*.name, 'publish-artifacts') 
          }}"
          echo "artifacts_publish_enabled=$artifacts_publish_enabled"
          echo "artifacts_publish_enabled=$artifacts_publish_enabled" >> "$GITHUB_OUTPUT"
