name: basic-steps

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    env:
      gradle_cmd: "./gradlew --parallel --console=plain --no-watch-fs -s "
      is_pull_request: github.event_name == 'pull_request'

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test condition
        run: ls -la .
          ../
          && pwd
