name: basic-steps

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest

    steps:
#      - name: all
#        run: echo ${{ toJSON(github) }}

      - name: all workflow
        run: echo ${{ toJSON(github.workflow) }}

  next-job:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
#      - name: all
#        run: echo ${{ toJSON(github) }}

      - name: all workflow
        run: echo ${{ toJSON(github.workflow) }}
