name: basic-steps

on:
  workflow_call:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: sleep 5 && echo 1
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: sleep 5 && echo 1

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: sleep 5 && echo 1

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: sleep 5 && echo 1

  job-final:
    needs:
      - *
    runs-on: ubuntu-latest
    steps:
      - name: step
        run: sleep 5 && echo 1
