name: Main branch checks

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:

#  check-main:
#    uses: ./.github/workflows/base-ci.yml

  js-test:
    - runs-on: ubuntu-latest
      steps:
        - uses: actions/github-script@v7
          id: my-script
          with:
            result-encoding: string
            script: console.log('azazaza')
