name: Main branch checks

on:
  push:
    branches:
      - 'main'
      - 'develop'



jobs:

#  check-main:
#    uses: ./.github/workflows/base-ci.yml
  create-release:
    runs-on: ubuntu-latest
    steps:

      - name: Clone project
        uses: actions/checkout@v3

      - name: validate test
        uses: ./.github/validation
