name: Main branch checks

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:

  check-main:
    uses: ./.github/workflows/base-ci.yml

  job-final:
    runs-on: ubuntu-latest
    steps:
      - name: call composite action with required arg
        uses: ./.github/action-composite
