name: Publish

on:
  pull_request:
    types: [ labeled ]
    branches:
      - '*'

jobs:

  build-and-test:
    if: ${{ github.event.label.name == 'publish' }}
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
