name: Pull Request

on:
  pull_request:
    branches:
      - '*'
  repository_dispatch:
    types: [ publish-artifacts,  my-event ]

jobs:


  event-data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}


  build-and-test:
    if: false # <------------------------------------------------
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
