name: Pull Request

on:
  pull_request:
    branches:
      - '*'
  repository_dispatch:
    types: [ publish-artifacts ]

jobs:

  build-and-test:
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
