name: Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:

  another:
    runs-on: ubuntu-latest
    steps:
    - name: pr
      if: ${{ github.event.pull_request }}
      run: echo 'pull_request'

    - name: wc
      if: ${{ github.event.workflow_call }}
      run: echo 'workflow_call'

  build-and-test:
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
