name: Pull Request

on:
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
      labeled,
    ]
    branches:
      - '*'
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:

  health:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}


  event-data:
    if:
      ${{
      github.event_name != 'pull_request' || 
        github.event.action != 'labeled' ||
        (github.event.action == 'labeled' && github.event.label.name == 'publish-artifacts')
      }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'aaaaaaaaaaaaaaaaaaaaaaaaa'


  build-and-test:
    if: false
    uses: ./.github/workflows/base-ci.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
