name: Release plugin

on:
  create:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build artifacts
        run: ./gradlew assemble

      - name: Get version
        id: release_version
        run: |
          echo ::set-output name=version::$(grep 'version=' gradle.properties | cut -d '=' -f 2)

      - name: debug step
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "version=${{ steps.release_version.outputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge main into develop'
          title: 'Merge main into develop'
          branch: develop
          body: 'This is an automated pull request created by the release process.'


      - name: Create Github release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          draft: true
