name: Release plugin

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

#      - name: Build artifacts
#        run: ./gradlew check assemble

      - name: Get version
        id: release_version
        run: |
          echo ::set-output name=version::$(grep 'version=' gradle.properties | cut -d '=' -f 2)
          echo "Obtained version from gradle.properties: '${{ steps.release_version.outputs.version }}'"

      - name: Adding tag ${{ steps.release_version.outputs.version }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.release_version.outputs.version }}"
          tag_exists_error: true
          message: "Latest release"

      - name: Create PR main to develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'main'
          destination_branch: 'develop'
          pr_title: 'Merge main to develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          draft: true
