name: Release plugin

on:
  push:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew assemble

      - name: Build artifacts
        run: ./gradlew assemble

      - name: Get version
        id: release_version
        run: |
          echo ::set-output name=version::$(grep 'version=' gradle.properties | cut -d '=' -f 2)

      - name: Create Github release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          draft: true


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge main into develop'
          title: 'Merge main into develop'
          branch: develop
          body: 'This is an automated pull request created by the release process.'
