name: Staging Deploy
run-name: Deploy by ${{ github.event.inputs.actor || github.actor }}

on:
  workflow_dispatch:
    inputs:
      actor:
        description: '11'
        default: ''
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: call composite action with required arg
        uses: ./.github/action-composite
        env:
          ACTOR: ${{ github.event.inputs.actor || github.actor }}
        with:
          some: $ACTOR
